version: '3'

services:
    # PostgreSQL
    db:
        image: postgres:12
        container_name: modulector_dev_db
        restart: always
        ports:
            - 5432:5432
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        environment:
            # IMPORTANT: these three params must be the same than POSTGRES_USERNAME, POSTGRES_PASSWORD, POSTGRES_DB
            # below in 'web' service respectively
            POSTGRES_USER: root
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: modulector
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./config/postgres/postgres.conf:/etc/postgresql/postgresql.conf

    # Web-based DB admin interface for MySQL management
    adminer:
        image: adminer
        container_name: modulector_dev_adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    postgres_data:
