version: '3'

services:
    # PostgreSQL (empty DB)
    db_modulector:
        image: postgres:16
        container_name: modulector_dev_db
        restart: always
        ports:
            - '5432:5432'
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        environment:
            # IMPORTANT: these three params must be the same as POSTGRES_USERNAME, POSTGRES_PASSWORD, POSTGRES_DB
            # below in 'web' service respectively
            POSTGRES_USER: 'modulector'
            POSTGRES_PASSWORD: 'modulector'
            POSTGRES_DB: 'modulector'
        volumes:
            - modulector_postgres_data:/var/lib/postgresql/data/
            - ./config/postgres/postgres.conf:/etc/postgresql/postgresql.conf

# Uncomment if using empty Postgres service
volumes:
    modulector_postgres_data:
        external:
            name: 'modulector_postgres_data'
