version: '3'

services:
    # PostgreSQL
    db:
      image: omicsdatascience/modulector-db:2.0.0
      # Uncomment this to add your custom config
      # volumes:
      #     - ./config/postgres/postgres.conf:/etc/postgresql/postgresql.conf

    # Django Proxy Server
    nginx:
        image: nginx:1.23.3
        ports:
            - "80:8000"
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - web

    # Django Backend Server
    web:
        image: omicsdatascience/modulector:2.0.3
        depends_on:
            - db
        environment:
            # Django
            DJANGO_SETTINGS_MODULE: 'ModulectorBackend.settings_prod'
            POSTGRES_HOST: 'db' # Name of the modulector-db service previously defined

            # CSRF. Django 4.x need this.
            # Hosts separated by comma ('http://', 'https://' prefixes are mandatory)
            # Example: CSRF_TRUSTED_ORIGINS: 'http://127.0.0.1', 'http://127.0.0.1,https://127.0.0.1:8000', etc
            CSRF_TRUSTED_ORIGINS: ''
