version: '3'

services:
    # PostgreSQL
    db:
        image: postgres:12
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        environment:
            # IMPORTANT: these three params must be the same than POSTGRES_USERNAME, POSTGRES_PASSWORD, POSTGRES_DB
            # below in 'web' service respectively
            POSTGRES_USER: ''
            POSTGRES_PASSWORD: ''
            POSTGRES_DB: 'modulector'
        volumes:
            - modulector_postgres_data:/var/lib/postgresql/data/
            - ./config/postgres/postgres.conf:/etc/postgresql/postgresql.conf

    # Django Proxi Server
    nginx:
        image: nginx:1.19
        ports:
            - 80:8000
        volumes:
            - ./:/src
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - ./static:/static
        depends_on:
            - web

    # Django Backend Server
    web:
        image: omicsdatascience/modulector:1.4
        restart: always
        # TODO: add frontend compilation when React code is ready
        depends_on:
            - db
        environment:
            # Django
            DJANGO_SETTINGS_MODULE: 'ModulectorBackend.settings_prod'

            # PostgreSQL DB connection parameters (MUST match the parameters defined in the "db" service above)
            POSTGRES_USERNAME: ''
            POSTGRES_PASSWORD: ''
            POSTGRES_HOST: 'db'
            POSTGRES_PORT: 5432
            POSTGRES_DB: 'modulector'
            LOAD_DATA: 1

volumes:
    modulector_postgres_data:
        external:
            name: 'modulector-backend_modulector_postgres_data'
