# Generated by Django 3.0.8 on 2020-09-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mirna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirna_code', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MirnaSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site_url', models.CharField(max_length=200)),
                ('min_score', models.DecimalField(decimal_places=4, max_digits=20)),
                ('max_score', models.DecimalField(decimal_places=4, max_digits=20)),
                ('score_interpretation', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('synchronization_date', models.DateTimeField()),
                ('file_separator', models.CharField(choices=[(',', 'Comma'), (';', 'Semicolon'), ('\t', 'Tab'), (':', 'Colon'), (' ', 'White space')], default='\t', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MirnaXGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pubmed_id', models.CharField(max_length=100, null=True)),
                ('pubMedUrl', models.CharField(max_length=300, null=True)),
                ('mirna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulector.Mirna')),
                ('mirna_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulector.MirnaSource')),
            ],
            options={
                'db_table': 'modulector_mirnaxgen',
            },
        ),
        migrations.CreateModel(
            name='MirnaColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.BigIntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=100, null=True)),
                ('field_to_map', models.CharField(blank=True, max_length=50, null=True)),
                ('mirna_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirnacolumns', to='modulector.MirnaSource')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
