# Generated by Django 3.0.8 on 2020-08-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mirna',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mirna_code', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MirnaSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('site_url', models.CharField(max_length=200)),
                ('min_score', models.DecimalField(decimal_places=4, max_digits=20)),
                ('max_score', models.DecimalField(decimal_places=4, max_digits=20)),
                ('score_interpretation', models.TextField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('synchronization_date', models.DateTimeField()),
                ('file_type', models.CharField(max_length=50)),
                ('file_separator', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MirnaXGen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gen', models.CharField(db_index=True, max_length=50)),
                ('score', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pubmed_id', models.CharField(max_length=100, null=True)),
                ('pubMedUrl', models.CharField(max_length=300, null=True)),
                ('mirnaSourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulector.MirnaSource')),
                ('mirna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulector.Mirna')),
            ],
        ),
        migrations.CreateModel(
            name='MirnaColumns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.BigIntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=100, null=True)),
                ('field_to_map', models.CharField(blank=True, max_length=50, null=True)),
                ('mirna_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulector.MirnaSource')),
            ],
        ),
    ]
