# Generated by Django 3.0.8 on 2020-09-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldRefSeqMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.CharField(max_length=40, unique=True)),
                ('new_value', models.CharField(max_length=40)),
            ],
        ),
    ]
