# Generated by Django 3.0.8 on 2020-08-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirnacolumns',
            old_name='mirna_source_id',
            new_name='mirna_source',
        ),
        migrations.RenameField(
            model_name='mirnaxgen',
            old_name='mirna_id',
            new_name='mirna',
        ),
        migrations.RenameField(
            model_name='mirnaxgen',
            old_name='mirnaSourceId',
            new_name='mirna_source',
        ),
    ]
