# Generated by Django 4.2.11 on 2026-08-07 15:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# modulector.migrations.0035_auto_20230112_2319
# modulector.migrations.0036_auto_20230116_2049
# modulector.migrations.0041_auto_20240410_1918
# modulector.migrations.0042_mirbaseidmirna_previous_mature_mirna
# modulector.migrations.0043_mirtarbase_1915
# modulector.migrations.0046_auto_20260807_1436
# modulector.migrations.0047_auto_20260807_1457

import os
import subprocess
import csv
import pathlib
import pandas as pd
from fasta_reader import read_fasta
from datetime import datetime
from tqdm import tqdm
import tqdm as tqdm_module
from django.db import connection, transaction

def import_methylation_epic_v2(apps, _schema_editor):
    """
    Import the Illumina Infinium MethylationEPIC BeadChip (EPIC) V2 array database.
    The tables that are created are:
        modulector_methylation_epic_v2: basic info of the CpG methylation site
        modulector_methylation_ucsc_cpg_island: info relating the methylation site to the nearest CpG islands.
        modulector_methylation_ucsc_refgene: info relating the methylation site to other genetic information like genes and transcripts according to RefSeq
        modulector_methylation_gencode: info relating the methylation site to other genetic information such as genes and transcripts according to Gencode
    """
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    db_path = os.path.join(parent_dir, "files/EPIC.csv")

    print("\n--- Loading Methylation EPIC V2 database ---")
    MethylationEPIC = apps.get_model(app_label='modulector', model_name='MethylationEPIC')
    MethylationUCSC_CPGIsland = apps.get_model(app_label='modulector', model_name='MethylationUCSC_CPGIsland')
    MethylationUCSCRefGene = apps.get_model(app_label='modulector', model_name='MethylationUCSCRefGene')
    MethylationGencode = apps.get_model(app_label='modulector', model_name='MethylationGencode')

    batch_size = 5000
    epic_batch = []
    related_data_batch = []
    
    def process_batch():
        if not epic_batch:
            return
            
        # Bulk create MethylationEPIC. In PostgreSQL, this assigns the .id to the instances.
        created_epics = MethylationEPIC.objects.bulk_create(epic_batch)
        
        islands_to_create = []
        ucscrefseq_to_create = []
        gencode_to_create = []

        for epic, related_data in zip(created_epics, related_data_batch):
            # CPG Islands
            islands_values, relation_values = related_data['islands']
            if len(islands_values) == len(relation_values) and len(relation_values) > 0:
                islands_to_create.extend([
                    MethylationUCSC_CPGIsland(
                        ucsc_cpg_island_name=islands_values[i],
                        relation_to_ucsc_cpg_island=relation_values[i],
                        methylation_epic_v2_ilmnid=epic
                    )
                    for i in range(len(relation_values))
                    if islands_values[i].startswith("chr")
                ])
                
            # UCSC RefGene
            ucscrefseq_group_values, ucscrefseq_name_values, ucscrefseq_accession_values = related_data['refseq']
            if len(ucscrefseq_group_values) == len(ucscrefseq_name_values) == len(ucscrefseq_accession_values):
                ucscrefseq_to_create.extend([
                    MethylationUCSCRefGene(
                        ucsc_refgene_group=ucscrefseq_group_values[u],
                        ucsc_refgene_name=ucscrefseq_name_values[u],
                        ucsc_refgene_accession=ucscrefseq_accession_values[u],
                        methylation_epic_v2_ilmnid=epic
                    )
                    for u in range(len(ucscrefseq_name_values))
                    if len(ucscrefseq_group_values[u]) > 0
                ])

            # Gencode
            gencode_group_values, gencode_name_values, gencode_accession_values = related_data['gencode']
            if len(gencode_group_values) == len(gencode_name_values) == len(gencode_accession_values):
                gencode_to_create.extend([
                    MethylationGencode(
                        gencode_group=gencode_group_values[i],
                        gencode_name=gencode_name_values[i],
                        gencode_accession=gencode_accession_values[i],
                        methylation_epic_v2_ilmnid=epic
                    )
                    for i in range(len(gencode_name_values))
                    if len(gencode_group_values[i]) > 0
                ])
                
        # Bulk create related records
        if islands_to_create:
            MethylationUCSC_CPGIsland.objects.bulk_create(islands_to_create)
        if ucscrefseq_to_create:
            MethylationUCSCRefGene.objects.bulk_create(ucscrefseq_to_create)
        if gencode_to_create:
            MethylationGencode.objects.bulk_create(gencode_to_create)
            
        epic_batch.clear()
        related_data_batch.clear()

    with open(db_path, "r", encoding='utf-8') as record:
        # Skip the first 7 commented rows
        for _ in range(7):
            next(record, None)
            
        csvreader_object = csv.DictReader(record, dialect='excel', delimiter=",")
        
        for row in tqdm_module.tqdm(csvreader_object, desc="EPIC records"):
            if row.get("IlmnID", "").startswith("cg"):
                epic = MethylationEPIC(
                    ilmnid=row["IlmnID"],
                    name=row.get("Name", ""),
                    strand_fr=row.get("Strand_FR", ""),
                    chr=row.get("CHR", ""),
                    mapinfo=row.get("MAPINFO", 0) or 0,
                    methyl450_loci=row.get("Methyl450_Loci", ""),
                    methyl27_loci=row.get("Methyl27_Loci", ""),
                    epicv1_loci=row.get("EPICv1_Loci", "")
                )
                epic_batch.append(epic)
                
                related_data_batch.append({
                    'islands': (row.get("UCSC_CpG_Islands_Name", "").split(";"), row.get("Relation_to_UCSC_CpG_Island", "").split(";")),
                    'refseq': (row.get("UCSC_RefGene_Group", "").split(";"), row.get("UCSC_RefGene_Name", "").split(";"), row.get("UCSC_RefGene_Accession", "").split(";")),
                    'gencode': (row.get("GencodeV41_Group", "").split(";"), row.get("GencodeV41_Name", "").split(";"), row.get("GencodeV41_Accession", "").split(";"))
                })
                
                if len(epic_batch) >= batch_size:
                    process_batch()
                    
        # Process any remaining records
        process_batch()




def import_mirbase(apps, _schema_editor):
    """Import the mirBase database to the tables: modulector_mirna and modulector_mirbaseidmirna"""
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    db_mature_path = os.path.join(parent_dir, "files/mature.fa")  # Download DB from miRBase for mature miRNAs
    db_hairpin_path = os.path.join(parent_dir, "files/hairpin.fa")  # Download DB from miRBase for hairpin miRNAs
    # Go to https://www.mirbase.org/ftp.shtml to download both previous datasets
    print("\n--- Loading miRBase database ---")
    Mirna = apps.get_model(app_label='modulector', model_name='Mirna')
    MirbaseIdMirna = apps.get_model(app_label='modulector', model_name='MirbaseIdMirna')

    for item in tqdm(list(read_fasta(db_mature_path)), desc="miRBase mature records"):
        defline = item.defline
        if "Homo sapiens" in defline:
            data = defline.split(" ")
            mirbase_id = data[0]
            mimat_id = data[1]
            sequence = item.sequence
            Mirna.objects.create(mirna_code=mirbase_id, mirna_sequence=sequence)
            MirbaseIdMirna.objects.create(mirbase_accession_id=mimat_id, mature_mirna=mirbase_id)

    for item in tqdm(list(read_fasta(db_hairpin_path)), desc="miRBase hairpin records"):
        defline = item.defline
        if "Homo sapiens" in defline:
            data = defline.split(" ")
            mirbase_id = data[0]
            mimat_id = data[1]
            MirbaseIdMirna.objects.create(mirbase_accession_id=mimat_id, mature_mirna=mirbase_id)


def import_mirdip(apps, _schema_editor):
    """It updates the mirDIP database in the table modulector_mirnaxgene. It also adds the miRNAs to the modulector_mirna table, without sequence, in case it is not found.
    Columns for file : files/mirDIP_Unidirectional_search.txt
        GENE_SYMBOL
        MICRORNA
        SOURCE_NUMBER
        INTEGRATED_RANK
        SOURCES
        SCORE_CLASS
    Example:
        "SPRYD3","hsa-miR-15a-5p",15,+9. 11060805626107E-001, "Cupid|MBStar|MirTar2|MultiMiTar|PACCMIT|bitargeting_May_2021|miRTar2GO|MirAncesTar|miranda_May_2021|mirbase|miRDB_v6|mirmap_May_2021|MiRNATIP|mirzag|TargetScan_v7_2", "V"
    """
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    mirdip_file_path = os.path.join(parent_dir, "files/mirDIP_Unidirectional_search.txt")

    print("\n--- Loading mirDIP database ---")
    MirnaXGene = apps.get_model(app_label='modulector', model_name='MirnaXGene')
    Mirna = apps.get_model(app_label='modulector', model_name='Mirna')
    MirnaSource = apps.get_model(app_label='modulector', model_name='MirnaSource')


    source = MirnaSource.objects.filter(name='mirdip')
    if not source:
        from django.utils import timezone
        source_mirdip = MirnaSource.objects.create(
            name='mirdip',
            site_url='http://ophid.utoronto.ca/mirDIP/',
            min_score=0.0,
            max_score=1.0,
            score_interpretation='Higher is better',
            description='mirDIP database',
            synchronization_date=timezone.now(),
            file_separator='\t'
        )
    else:
        source_mirdip = source[0]  # If there would be more than one, either of the two could be assigned

    not_found_count = 0
    chunk_size = 100000

    try:
        total_rows = int(subprocess.check_output(['wc', '-l', mirdip_file_path]).split()[0]) - 1
        total_chunks = (total_rows // chunk_size) + 1
    except Exception:
        total_chunks = None

    chunks = pd.read_csv(
        mirdip_file_path,
        header=0,
        names=['GENE_SYMBOL', 'MICRORNA', 'SOURCE_NUMBER', 'INTEGRATED_RANK', 'SOURCES', 'SCORE_CLASS'],
        chunksize=chunk_size
    )

    for chunk in tqdm(chunks, total=total_chunks, desc='mirDIP records'):
        unique_mirnas = chunk['MICRORNA'].dropna().unique()
        
        # Get existing miRNAs for this chunk
        existing_mirnas = dict(Mirna.objects.filter(mirna_code__in=unique_mirnas).values_list('mirna_code', 'id'))
        
        # Find missing miRNAs
        missing_mirna_codes = set(unique_mirnas) - set(existing_mirnas.keys())
        if missing_mirna_codes:
            not_found_count += len(missing_mirna_codes)
            new_mirnas = [Mirna(mirna_code=code, mirna_sequence=None) for code in missing_mirna_codes]
            Mirna.objects.bulk_create(new_mirnas)
            
            # Re-fetch the newly created ones to get their IDs
            new_existing = dict(Mirna.objects.filter(mirna_code__in=missing_mirna_codes).values_list('mirna_code', 'id'))
            existing_mirnas.update(new_existing)

        # Prepare MirnaXGene records
        mirnaxgenes = [
            MirnaXGene(
                gene=row.GENE_SYMBOL,
                score=row.INTEGRATED_RANK,
                sources=row.SOURCES,
                score_class=row.SCORE_CLASS,
                mirna_source_id=source_mirdip.id,
                mirna_id=existing_mirnas[row.MICRORNA]
            )
            for row in chunk.itertuples(index=False)
            if pd.notna(row.MICRORNA)
        ]
        
        # Bulk create MirnaXGene for this chunk
        MirnaXGene.objects.bulk_create(mirnaxgenes, batch_size=5000)
    print(f'{not_found_count} miRNAs were found in mirDIP but not in mature miRBase miRNAs.')




def update_hmdd_v4(apps, schema_editor):
    """ Update the version of the HMDD database to version 4.0 """
    MirnaDisease = apps.get_model('modulector', 'MirnaDisease')

    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    print("\n--- Loading HMDD v4 database ---")
    file_path = os.path.join(parent_dir, "files/disease_hmdd.txt")
    delimiter = "\t"
    # loading files
    data = pd.read_csv(filepath_or_buffer=file_path,
                       delimiter=delimiter, encoding="ISO-8859-1")
    entities = []
    for index, row in tqdm(data.iterrows(), total=len(data), desc="HMDD v4 records"):
        category, pmid, mirna, disease, description = row
        # category is the Category codes assigned by the HMDD database to classify diseases

        # This line is in charge of capitalizing the R for the mirna, we must treat it as mature
        # In the file are all lowercase, but in the website which provides said file, they
        # are listed as mature. This will also maintain consistency from our side.
        mirna = mirna.lower()[:6].lower() + mirna.lower()[6:].capitalize()
        # correcting fields because the send quotes sometimes
        disease = disease.replace("\"", "")
        description = description.replace("\"", "")
        mirna_disease = MirnaDisease(category=category, mirna=mirna,
                                        disease=disease, pubmed_id=pmid, description=description)
        entities.append(mirna_disease)
    MirnaDisease.objects.bulk_create(entities)

    assert MirnaDisease.objects.count() == data.shape[0]




def load_mirna_mature(apps, _schema_editor):
    """Truncates modulector_mirbaseidmirna and reloads it from files/mirna_mature.txt.
    Only rows where mature_mirna starts with 'hsa' are imported (homo sapiens).
    File columns (whitespace-separated): id, mature_mirna, [previous_mature_mirna], mirbase_accession_id, ...
    In some rows the previous_mature_mirna column is absent.
    If previous_mature_mirna contains multiple values separated by ';', one row is
    inserted for each value.
    """
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    file_path = os.path.join(parent_dir, "files", "mirna_mature.txt")

    MirbaseIdMirna = apps.get_model(app_label='modulector', model_name='MirbaseIdMirna')

    batch_size = 5000
    records = []
    print("\n--- Loading miRNA mature database ---")
    with open(file_path, encoding='utf-8', errors='replace') as input_stream:
        for line in tqdm(input_stream, desc='miRNA mature records'):
            parts = line.split()
            if len(parts) < 3:
                continue

            mature_mirna = parts[1]
            if not mature_mirna.startswith('hsa'):
                continue

            if parts[2].startswith('MIMAT'):
                previous_mature_mirna = ''
                mirbase_accession_id = parts[2]
            else:
                previous_mature_mirna = parts[2]
                mirbase_accession_id = parts[3]

            previous_values = [value.strip() for value in previous_mature_mirna.split(';') if value.strip()]
            if not previous_values:
                previous_values = ['']

            for previous_value in previous_values:
                records.append(MirbaseIdMirna(
                    mirbase_accession_id=mirbase_accession_id,
                    mature_mirna=mature_mirna,
                    previous_mature_mirna=previous_value,
                ))

    total_batches = (len(records) + batch_size - 1) // batch_size
    for i in tqdm(range(0, len(records), batch_size), desc="miRNA mature inserting", total=total_batches, unit="batch"):
        MirbaseIdMirna.objects.bulk_create(records[i:i + batch_size])

    




def load_mirtarbase_data(apps, _schema_editor):
    """
    Truncates the modulector_mirtarbaseinteraction table and reloads it from files/hsa_MTI.csv.
    Cleans float fields (e.g. 17179747.0 to 17179747) coming from the CSV.
    """
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    file_path = os.path.join(parent_dir, "files", "hsa_MTI.csv")

    MirTarBaseInteraction = apps.get_model(app_label='modulector', model_name='MirTarBaseInteraction')

    batch_size = 5000
    records = []
    total_inserted = 0

    print("\n--- Loading miRTarBase database ---")
    with open(file_path, mode='r', encoding='utf-8-sig') as input_stream:
        reader = csv.DictReader(input_stream)
        
        with tqdm(desc='miRTarBase records', unit='row') as pbar:
            for row in reader:
                # Clean PMID (from "17179747.0" to "17179747")
                raw_pmid = row.get('References (PMID)', '')
                clean_pmid = str(int(float(raw_pmid))) if raw_pmid and str(raw_pmid).lower() != 'nan' else ''

                # Clean Entrez ID (from "6541.0" to "6541")
                raw_entrez = row.get('Target Gene (Entrez ID)', '')
                clean_entrez = str(int(float(raw_entrez))) if raw_entrez and str(raw_entrez).lower() != 'nan' else ''

                raw_experiments = row.get('Experiments', '')
                experiments_list = [exp.strip() for exp in raw_experiments.split('//') if exp.strip()] if raw_experiments else []

                records.append(MirTarBaseInteraction(
                    mirtarbase_id=row.get('miRTarBase ID', ''),
                    mirna=row.get('miRNA', ''),
                    gene=row.get('Target Gene', ''),
                    target_gene_entrez_id=clean_entrez,
                    experiments=experiments_list,
                    support_type=row.get('Support Type', ''),
                    pmid=clean_pmid
                ))
                
                if len(records) >= batch_size:
                    MirTarBaseInteraction.objects.bulk_create(records)
                    total_inserted += len(records)
                    records.clear()
                    
                pbar.update(1)
                
        # Insert any remaining records
        if records:
            MirTarBaseInteraction.objects.bulk_create(records)
            total_inserted += len(records)
            records.clear()

    




def load_gene_aliases(apps, schema_editor):
    GeneAliases = apps.get_model('modulector', 'GeneAliases')
    
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    file_path = os.path.join(parent_dir, "files/hgnc_complete_set.txt")
    
    print("\n--- Loading HGNC Gene Aliases database ---")
    data = pd.read_csv(
        filepath_or_buffer=file_path, 
        sep="\t", 
        encoding="utf-8", 
        usecols=['symbol', 'prev_symbol', 'alias_symbol'],
        dtype=str
    )
    
    data.rename(columns={
        'symbol': 'current', 
        'prev_symbol': 'old', 
        'alias_symbol': 'other'
    }, inplace=True)

    data = data[(data["old"].notnull() | data["other"].notnull())]
    
    entities_to_insert = []
    with transaction.atomic():
        for index, row in tqdm(data.iterrows(), total=len(data), desc="HGNC Gene Aliases records"):
            gene_symbol = row['current']
            old = row['old']
            new = row['other']
            
            # fix for specific case due to file interpretation
            if pd.isna(gene_symbol) and old == 'NAC' and pd.isna(new):
                gene_symbol = 'NA'
                
            if pd.isna(gene_symbol):
                continue
                
            gene_symbol = str(gene_symbol).strip()
            aliases = []
            
            if pd.notna(old) and str(old).strip() != "":
                # Remove any quotation marks and standardize the separator to a pipe.
                old_clean = str(old).replace('"', '').replace(',', '|')
                aliases.extend([a.strip() for a in old_clean.split("|") if a.strip()])
                
            if pd.notna(new) and str(new).strip() != "":
                new_clean = str(new).replace('"', '').replace(',', '|')
                aliases.extend([a.strip() for a in new_clean.split("|") if a.strip()])
                
            for alias in aliases:
                entities_to_insert.append(GeneAliases(gene_symbol=gene_symbol, alias=alias))
                
        GeneAliases.objects.bulk_create(entities_to_insert, batch_size=5000)



def load_drugs(apps, schema_editor):
    MirnaDrug = apps.get_model('modulector', 'MirnaDrug')
    
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    file_path = os.path.join(parent_dir, "files/drugs.xls")
    
    print("\n--- Loading Drugs database ---")
    data = pd.read_excel(file_path)
    data = data[data["Species"].str.contains("Homo sapiens")]
    data = data.drop(['DB', 'CID', 'Species', 'Year'], axis=1)
    
    entities = []
    with transaction.atomic():
        for index, row in tqdm(data.iterrows(), total=len(data), desc="Drugs records"):
            mature_mirna, mirbase_accession_id, small_molecule, fda, detection_method, condition, pmid, reference, suppport, expression_pattern = row
            # We must prepend the hsa because the file we process does not have it
            mature_mirna = 'hsa-' + str(mature_mirna)
            fda = (fda == 'approved')
            if pd.isna(mirbase_accession_id):
                mirbase_accession_id = ''

            mirna_drug = MirnaDrug(mature_mirna=mature_mirna, mirbase_accession_id=mirbase_accession_id,
                                   small_molecule=small_molecule,
                                   fda_approved=fda, detection_method=detection_method, condition=condition,
                                   pubmed_id=pmid,
                                   reference=reference, support=suppport, expression_pattern=expression_pattern)
            entities.append(mirna_drug)
            
        MirnaDrug.objects.bulk_create(entities)




def check_files_exist(apps, schema_editor):
    """Check that all required files exist before starting the migration."""
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    required_files = [
        "files/EPIC.csv",
        "files/mature.fa",
        "files/hairpin.fa",
        "files/mirDIP_Unidirectional_search.txt",
        "files/disease_hmdd.txt",
        "files/mirna_mature.txt",
        "files/hsa_MTI.csv",
        "files/hgnc_complete_set.txt",
        "files/drugs.xls",
    ]
    missing_files = [
        f for f in required_files
        if not os.path.exists(os.path.join(parent_dir, f))
    ]
    
    if missing_files:
        raise FileNotFoundError(f"Missing required data files for migration: {', '.join(missing_files)}")


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=check_files_exist,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=import_mirbase,
        ),
        migrations.RunPython(
            code=import_mirdip,
        ),
        migrations.RunPython(
            code=import_methylation_epic_v2,
        ),
        migrations.RunPython(
            code=update_hmdd_v4,
        ),
        migrations.RunPython(
            code=load_mirna_mature,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=load_mirtarbase_data,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=load_gene_aliases,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=load_drugs,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
