# Generated by Django 3.0.8 on 2020-08-15 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0002_auto_20200811_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirnacolumns',
            name='mirna_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirnacolumns', to='modulector.MirnaSource'),
        ),
    ]
