# Generated by Django 3.0.8 on 2020-08-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0003_auto_20200815_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirna',
            name='mirna_code',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
