# Generated by Django 3.0.8 on 2020-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0003_genesymbolmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirbaseIdMirna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirbase_id', models.CharField(max_length=20)),
                ('mature_mirna', models.CharField(max_length=30)),
            ],
        ),
    ]
