# Generated by Django 3.0.8 on 2020-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0004_auto_20200818_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mirnacolumns',
            options={'ordering': ['position']},
        ),
        migrations.AddIndex(
            model_name='mirnaxgen',
            index=models.Index(fields=['mirna'], name='idx_mirna'),
        ),
    ]
