# Generated by Django 3.0.8 on 2020-10-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0006_mirnadisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirnaDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirna', models.CharField(max_length=50)),
                ('mirbase_id', models.CharField(max_length=20)),
                ('small_molecule', models.CharField(max_length=100)),
                ('fda_approved', models.BooleanField()),
                ('detection_method', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('pmid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('reference', models.TextField()),
            ],
            options={
                'db_table': 'modulector_mirnadrugs',
            },
        ),
    ]
