# Generated by Django 3.0.8 on 2020-09-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0006_auto_20200822_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirnasource',
            name='score_interpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mirnaxgen',
            index=models.Index(fields=['mirna_source'], name='idx_mirna_source'),
        ),
        migrations.AlterModelTable(
            name='mirnaxgen',
            table='modulector_mirnaxgen',
        ),
    ]
