# Generated by Django 3.0.8 on 2020-09-12 14:43

from django.db import migrations, models


def set_file_separator(apps, schema_editor):
    """Prevents truncating error"""
    MirnaSource = apps.get_model('modulector', 'MirnaSource')
    for mirna_source in MirnaSource.objects.all():
        mirna_source.file_separator = '\t'
        mirna_source.save(update_fields=['file_separator'])


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0007_auto_20200909_0317'),
    ]

    operations = [
        migrations.RunPython(set_file_separator),
        migrations.AlterField(
            model_name='mirnasource',
            name='file_separator',
            field=models.CharField(choices=[(',', 'Comma'), (';', 'Semicolon'), ('\t', 'Tab'), (':', 'Colon'), (' ', 'White space')], default='\t', max_length=1),
        ),
    ]
