# Generated by Django 3.0.8 on 2020-10-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0008_mirnadrugs_expression_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirnadrugs',
            name='support',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
