# Generated by Django 3.0.8 on 2020-10-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0009_mirnadrugs_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirnadrugs',
            old_name='mirna',
            new_name='mature_mirna',
        ),
    ]
