# Generated by Django 3.0.8 on 2020-10-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0010_auto_20201022_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirnadrugs',
            name='small_molecule',
            field=models.TextField(),
        ),
    ]
