# Generated by Django 3.0.8 on 2020-10-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0011_auto_20201022_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirnadrugs',
            name='condition',
            field=models.TextField(),
        ),
    ]
