# Generated by Django 3.0.8 on 2020-11-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0013_auto_20201118_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirnadisease',
            old_name='pmid',
            new_name='pubmed_id',
        ),
        migrations.RenameField(
            model_name='mirnadrugs',
            old_name='pmid',
            new_name='pubmed_id',
        ),
    ]
