# Generated by Django 3.0.8 on 2021-01-18 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0014_auto_20201118_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirnaxgene',
            name='pubmed_id',
        ),
        migrations.RemoveField(
            model_name='mirnaxgene',
            name='pubmed_url',
        ),
        migrations.CreateModel(
            name='Pubmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.CharField(max_length=100, null=True)),
                ('pubmed_url', models.CharField(max_length=300, null=True)),
                ('mirnaxgene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubmed', to='modulector.MirnaXGene')),
            ],
        ),
    ]
