# Generated by Django 3.0.8 on 2021-01-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0015_auto_20210118_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubmed',
            old_name='mirnaxgene_id',
            new_name='mirnaxgene',
        ),
    ]
