# Generated by Django 3.0.8 on 2021-01-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0016_auto_20210118_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubmed',
            name='mirnaxgene',
        ),
        migrations.AddField(
            model_name='pubmed',
            name='gene',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pubmed',
            name='mirna_code',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
