# Generated by Django 3.0.8 on 2021-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0017_auto_20210118_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubmed',
            name='mirna_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
