# Generated by Django 3.0.8 on 2021-01-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0019_mirna_mirna_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirbaseidmirna',
            old_name='mirbase_id',
            new_name='mirbase_accession_id',
        ),
        migrations.RenameField(
            model_name='mirnadrugs',
            old_name='mirbase_id',
            new_name='mirbase_accession_id',
        ),
    ]
