# Generated by Django 3.0.8 on 2021-02-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0021_delete_url_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirnaxgene',
            name='sources',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
