# Generated by Django 3.0.8 on 2021-02-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0022_mirnaxgene_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirnaxgene',
            name='score_class',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
