# Generated by Django 3.0.8 on 2021-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0023_mirnaxgene_score_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirnaxgene',
            name='sources',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
