# Generated by Django 3.0.8 on 2021-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0024_auto_20210212_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirnaxgene',
            name='sources',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
