# Generated by Django 3.0.8 on 2021-02-22 18:13
# IMPORTANT: this migration fixes a problem with multiple URL templates which were
# used in a previous version of Modulector

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0025_auto_20210212_1725'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM MODULECTOR_URLTEMPLATE WHERE name != 'mirbase'")
    ]
