# Generated by Django 3.0.8 on 2021-03-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0026_auto_20210222_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MirnaDrugs',
            new_name='MirnaDrug',
        ),
    ]
