# Generated by Django 3.0.8 on 2021-03-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0027_auto_20210309_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'modulector_gene_aliases',
            },
        ),
    ]
