# Generated by Django 3.0.8 on 2021-03-30 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0030_auto_20210324_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='unsubscribe_token',
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='unsubscribe_token',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='gene',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='record_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 0, 44, 7, 606369, tzinfo=utc)),
        ),
    ]
