# Generated by Django 3.0.8 on 2021-03-31 00:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0031_auto_20210330_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='gene',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='record_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 0, 14, 25, 603476, tzinfo=utc)),
        ),
    ]
