# Generated by Django 3.1.13 on 2023-01-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0033_auto_20210427_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethylationEPIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilmnid', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=15)),
                ('strand_fr', models.CharField(max_length=1)),
                ('chr', models.CharField(max_length=5)),
                ('mapinfo', models.BigIntegerField()),
                ('methyl450_loci', models.CharField(max_length=21)),
                ('methyl27_loci', models.CharField(max_length=21)),
                ('epicv1_loci', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='MethylationUCSCRefGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucsc_refgene_group', models.CharField(max_length=12)),
                ('ucsc_refgene_name', models.CharField(max_length=30)),
                ('ucsc_refgene_accession', models.CharField(max_length=20)),
                ('methylation_epic_v2_ilmnid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulector.methylationepic')),
            ],
        ),
        migrations.CreateModel(
            name='MethylationUCSC_CPGIsland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucsc_cpg_island_name', models.CharField(max_length=30)),
                ('relation_to_ucsc_cpg_island', models.CharField(max_length=8)),
                ('methylation_epic_v2_ilmnid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulector.methylationepic')),
            ],
        ),
        migrations.CreateModel(
            name='MethylationGencode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gencode_group', models.CharField(max_length=12)),
                ('gencode_name', models.CharField(max_length=30)),
                ('gencode_accession', models.CharField(max_length=20)),
                ('methylation_epic_v2_ilmnid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulector.methylationepic')),
            ],
        ),
    ]
