# Generated by Django 4.1.7 on 2023-07-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0037_alter_genealiases_id_alter_genesymbolmapping_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methylationepic',
            name='epicv1_loci',
            field=models.CharField(db_index=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='methylationepic',
            name='ilmnid',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='methylationepic',
            name='methyl27_loci',
            field=models.CharField(db_index=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='methylationepic',
            name='methyl450_loci',
            field=models.CharField(db_index=True, max_length=21),
        ),
        migrations.AlterField(
            model_name='methylationepic',
            name='name',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
