# Generated by Django 4.2.2 on 2023-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0038_alter_methylationepic_epicv1_loci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methylationepic',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
