# Generated by Django 4.2.2 on 2023-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0039_alter_methylationepic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirnaxgene',
            name='gene',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mirnaxgene',
            name='score',
            field=models.DecimalField(db_index=True, decimal_places=4, max_digits=20),
        ),
    ]
