# Generated by Django 4.2.11 on 2024-04-10 19:18
import os
import pathlib
import pandas as pd
from django.db import migrations


def update_hmdd_v4(apps, schema_editor):
    """ Update the version of the HMDD database to version 4.0 """
    MirnaDisease = apps.get_model('modulector', 'MirnaDisease')

    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    print(parent_dir)
    file_path = os.path.join(parent_dir, "files/disease_hmdd.txt")
    delimiter = "\t"
    # loading files
    data = pd.read_csv(filepath_or_buffer=file_path,
                       delimiter=delimiter, encoding="ISO-8859-1")
    entities = []
    for index, row in data.iterrows():
        category, pmid, mirna, disease, description = row
        # category is the Category codes assigned by the HMDD database to classify diseases

        # This line is in charge of capitalizing the R for the mirna, we must treat it as mature
        # In the file are all lowercase, but in the website which provides said file, they
        # are listed as mature. This will also maintain consistency from our side.
        mirna = mirna.lower()[:6].lower() + mirna.lower()[6:].capitalize()
        # correcting fields because the send quotes sometimes
        disease = disease.replace("\"", "")
        description = description.replace("\"", "")
        mirna_disease = MirnaDisease(category=category, mirna=mirna,
                                        disease=disease, pubmed_id=pmid, description=description)
        entities.append(mirna_disease)
    MirnaDisease.objects.all().delete()
    MirnaDisease.objects.bulk_create(entities)

    assert MirnaDisease.objects.count() == data.shape[0]


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0040_alter_mirnaxgene_gene_alter_mirnaxgene_score'),
    ]

    operations = [
        migrations.RunPython(update_hmdd_v4),
    ]
