# Generated by Django 4.2.11 on 2026-07-08 19:15

import os
import pathlib
import csv
from django.db import migrations, models
from tqdm import tqdm


def load_mirtarbase_data(apps, _schema_editor):
    """
    Truncates the modulector_mirtarbaseinteraction table and reloads it from files/hsa_MTI.csv.
    Cleans float fields (e.g. 17179747.0 to 17179747) coming from the CSV.
    """
    parent_dir = pathlib.Path(__file__).parent.absolute().parent
    file_path = os.path.join(parent_dir, "files", "hsa_MTI.csv")

    print("\nReading hsa_MTI.csv...")
    MirTarBaseInteraction = apps.get_model(app_label='modulector', model_name='MirTarBaseInteraction')

    MirTarBaseInteraction.objects.all().delete()

    batch_size = 5000
    records = []

    with open(file_path, mode='r', encoding='utf-8-sig') as input_stream:
        reader = csv.DictReader(input_stream)
        rows = list(reader)

    with tqdm(rows, desc='Parsing CSV', unit='row') as pbar:
        for row in pbar:
            # Clean PMID (from "17179747.0" to "17179747")
            raw_pmid = row.get('References (PMID)', '')
            clean_pmid = str(int(float(raw_pmid))) if raw_pmid and str(raw_pmid).lower() != 'nan' else ''

            records.append(MirTarBaseInteraction(
                mirtarbase_id=row.get('miRTarBase ID', ''),
                mirna=row.get('miRNA', ''),
                gene=row.get('Target Gene', ''),
                experiments=row.get('Experiments', ''),
                support_type=row.get('Support Type', ''),
                pmid=clean_pmid
            ))

    total_batches = (len(records) + batch_size - 1) // batch_size
    print(f"Inserting {len(records)} HSA miRTarBase records in {total_batches} batches...")
    with tqdm(range(0, len(records), batch_size), desc='Inserting batches', unit='batch', total=total_batches) as pbar:
        for i in pbar:
            MirTarBaseInteraction.objects.bulk_create(records[i:i + batch_size])

    print(f"Done. {len(records)} records loaded into modulector_mirtarbaseinteraction.")


class Migration(migrations.Migration):
    dependencies = [
        ('modulector', '0042_mirbaseidmirna_previous_mature_mirna'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirTarBaseInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirtarbase_id', models.CharField(max_length=50)),
                ('mirna', models.CharField(db_index=True, max_length=100)),
                ('gene', models.CharField(db_index=True, max_length=100)),
                ('experiments', models.TextField()),
                ('support_type', models.CharField(max_length=100)),
                ('pmid', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['mirna', 'gene'], name='modulector__mirna_8c339f_idx')],
            },
        ),
        migrations.RunPython(load_mirtarbase_data),
    ]