# Generated by Django 4.2.11 on 2026-07-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulector', '0043_mirtarbase_1915'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mirtarbaseinteraction',
            new_name='modulector__mirna_27e058_idx',
            old_name='modulector__mirna_8c339f_idx',
        ),
    ]
