name: CI for prod enviroment with code analisis
on:
  push:
    - prod
jobs:
  sonar-and-docker:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Set testdb
      run: BASEDIR=$(pwd) ./tools/get_version.sh          
    - name: Modulector docker build
      run: echo "Building docker..."
