name: CI for check if version exist on docker registry
on:
  pull_request:
    branches:
      - "prod"
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: BASEDIR=$(pwd) ./tools/get_version.sh >> $GITHUB_ENV
      - name: Check modulector current version
        id: is_image_exist
        uses: tm-bverret/docker-exist-action@v1.1.2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ secrets.DOCKERHUB_USERNAME }}/modulector:${{ env.VERSION }}
      - name: modulector current version docker image exists?
        if: ((steps.is_image_exist.outputs.image_exist))
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This modulector version already exists on docker registry')
